// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYh9qF5odJ5lKHGfsX8w0p38TUzIrJukk',
    appId: '1:780732592304:web:225f65bf42c0b3beb28b75',
    messagingSenderId: '780732592304',
    projectId: 'shoplancer-ecb7b',
    authDomain: 'shoplancer-ecb7b.firebaseapp.com',
    databaseURL: 'https://shoplancer-ecb7b-default-rtdb.firebaseio.com',
    storageBucket: 'shoplancer-ecb7b.firebasestorage.app',
    measurementId: 'G-69RE0DMN81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzIaa1eG0tTXUq9FOSRxnm8IlAh-qLIU',
    appId: '1:780732592304:android:b5c95c7a731f570db28b75',
    messagingSenderId: '780732592304',
    projectId: 'shoplancer-ecb7b',
    databaseURL: 'https://shoplancer-ecb7b-default-rtdb.firebaseio.com',
    storageBucket: 'shoplancer-ecb7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-XNQEccE_WcclQwEch0lZa27VbV5EYWM',
    appId: '1:780732592304:ios:deba51e12601c7aeb28b75',
    messagingSenderId: '780732592304',
    projectId: 'shoplancer-ecb7b',
    databaseURL: 'https://shoplancer-ecb7b-default-rtdb.firebaseio.com',
    storageBucket: 'shoplancer-ecb7b.firebasestorage.app',
    iosBundleId: 'com.zahed.shoplanser',
  );

}