default_platform(:android)

platform :android do

  desc "Build and upload to Firebase App Distribution"

  lane :beta do
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build apk --release")

firebase_app_distribution(
  app: ENV["FIREBASE_APP_ID"],
  service_credentials_file: "../firebase-service-account.json",
  android_artifact_type: "APK",
  android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
  release_notes: <<~NOTES
    Branch: #{ENV["GITHUB_REF_NAME"]}
    Build: ##{ENV["GITHUB_RUN_NUMBER"]}
    Commit: #{ENV["GITHUB_SHA"]}
  NOTES
)
  end

  desc "Deploy to Google Play"

  lane :deploy do

    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build appbundle"

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

  end
end